import { ArrowRight, ArrowUpRight } from "lucide-react";
import { Link } from "wouter";
import { SectionEyebrow, SiteFooter, SiteHeader } from "@/components/SiteChrome";

const focusAreas = [
  ["01", "Connected employee records", "Bring documents and information into the moments people need them across the employee lifecycle."],
  ["02", "Purposeful system integration", "Shape secure, maintainable connections between OpenText content platforms and SAP SuccessFactors."],
  ["03", "Control without friction", "Design governed records and document flows that still feel straightforward for everyday users."],
  ["04", "Better employee experience", "Reduce fragmented journeys by making relevant information easier to find and action."],
] as const;

export default function OpenTextSuccessFactors() {
  return <div className="tw-root"><SiteHeader /><main>
    <section className="interior-hero interior-hero--visual" data-theme="dark"><div className="tw-container service-hero-grid"><div><SectionEyebrow>OpenText + SAP SuccessFactors integration</SectionEyebrow><h1 className="tw-display tw-display--xl">Put trusted content into the flow of people operations.</h1><p className="tw-lead">Connect enterprise content, employee data and the processes around them — without creating another disconnected layer for teams to manage.</p><a href="mailto:info@technowizltd.com?subject=TechnoWiz%20website%20enquiry" className="tw-btn tw-btn--mint">Explore the integration <ArrowRight /></a></div><div className="service-art"><img src="/manus-storage/opentext-sap-integration_5a9fc91c.png" alt="Abstract visualisation of connected enterprise systems" /></div></div></section>
    <section className="tw-band tw-section"><div className="tw-container"><div className="hp-head"><div><SectionEyebrow>One connected experience</SectionEyebrow><h2 className="tw-display tw-display--lg">HR decisions and their supporting documents, working together.</h2></div><p className="hp-head__copy">We help make the integration meaningful at the operating level: clear ownership, useful information flows and a structure that can evolve.</p></div><div className="integration-map"><article><span>01</span><h3>OpenText</h3><p>Content & records</p></article><i aria-hidden="true" /><article className="integration-map__middle"><span>02</span><h3>Integration layer</h3><p>Secure orchestration</p></article><i aria-hidden="true" /><article><span>03</span><h3>SAP SuccessFactors</h3><p>People operations</p></article></div></div></section>
    <section className="tw-band tw-band--alt tw-section"><div className="tw-container"><div className="hp-head"><div><SectionEyebrow>Designed around use</SectionEyebrow><h2 className="tw-display tw-display--lg">Make content a better part of the employee journey.</h2></div></div><div className="tw-services outcome-grid">{focusAreas.map(([number, title, detail]) => <article className="tw-card" key={number}><span className="tw-card__num">{number}</span><h3>{title}</h3><p>{detail}</p></article>)}</div></div></section>
    <section className="tw-band tw-section" data-theme="dark"><div className="tw-container split-heading"><div><SectionEyebrow>How we help</SectionEyebrow><h2 className="tw-display tw-display--lg">Integration needs more than a technical handshake.</h2></div><div className="integration-copy"><p>Technowiz brings experience in enterprise content management, workflow tools and third-party integrations. We work from the practical questions first: what should move, who should own it, how should it be controlled and where should it appear?</p><p>The result is an integration approach that supports process clarity today and leaves room to adapt tomorrow.</p><a href="mailto:info@technowizltd.com?subject=TechnoWiz%20website%20enquiry" className="tw-link">Talk through your landscape <ArrowUpRight /></a></div></div></section>
  </main><SiteFooter /></div>;
}
